volumes:
    vendor:
    node_modules:

services:
    nginx:
        build:
            context: ./docker/nginx
        depends_on:
            - fpm
            - mariadb
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./public:/src/public
            - ./docs:/src/docs
            - ./docker/nginx/logs:/logs
        environment:
            TZ: ${APP_TIMEZONE}
    cli:
        build:
            context: ./docker/cli
            args:
                PHP_VER: ${PHP_VER}
        depends_on:
            - mariadb
        volumes:
            - .:/src
            - node_modules:/src/node_modules
            - vendor:/src/vendor
        environment:
            TZ: ${APP_TIMEZONE}
    fpm:
        build:
            context: ./docker/fpm
            args:
                PHP_VER: ${PHP_VER}
                VITE_PORT: ${VITE_PORT}
        depends_on:
            - mariadb
        ports:
            - ${VITE_PORT}:${VITE_PORT}
        volumes:
            - .:/src
            - node_modules:/src/node_modules
            - vendor:/src/vendor
            - ./docker/ssl:/ssl
        environment:
            TZ: ${APP_TIMEZONE}
    mariadb:
        image: mariadb:latest
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
        environment:
            TZ: ${APP_TIMEZONE}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
